language: node_js
node_js:
  - "6"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_install:
  - npm install -g bower
  - bower install
script:
  - npm run test
  - npm run test:coverage
after_success:
  - npm run coveralls
